/* أدوات الإدارة — الدفعة 2: إدارة العقارات والحالات */
(function(){
  const wait=(fn,n=80)=>{if(fn())return;setTimeout(()=>wait(fn,n),n)};
  const data=()=>typeof listings!=='undefined'?(listings||[]):[];
  const labels={published:'متاح',sold:'مباع',rented:'مؤجّر'};
  const statusClass={published:'available',sold:'sold',rented:'rented'};
  const isAdmin=async()=>{try{const {data:{user}}=await db.auth.getUser();if(!user)return false;const {data:p}=await db.from('profiles').select('role').eq('id',user.id).single();return p?.role==='admin'}catch(_){return false}};
  function installStyle(){if(document.getElementById('adminToolsStyle'))return;const s=document.createElement('style');s.id='adminToolsStyle';s.textContent=`
  .admin-session-bar{position:fixed;z-index:95;top:12px;left:50%;transform:translateX(-50%);display:flex;align-items:center;gap:7px;padding:7px 9px;background:rgba(15,23,42,.94);backdrop-filter:blur(14px);border:1px solid rgba(255,255,255,.12);border-radius:16px;color:#fff;box-shadow:0 12px 32px rgba(0,0,0,.25);font:700 10px Cairo,Arial,sans-serif;direction:rtl}.admin-session-bar span{display:flex;align-items:center;gap:5px;padding:0 5px}.admin-session-bar span i{width:7px;height:7px;border-radius:50%;background:#31d39b;box-shadow:0 0 10px #31d39b}.admin-session-bar button{border:0;border-radius:10px;padding:7px 10px;background:#243047;color:#fff;font:700 9px Cairo,Arial,sans-serif;cursor:pointer}.admin-session-bar button:first-of-type{background:#087f68}
  .admin-dashboard{margin-top:16px}.admin-stats{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:9px;margin-bottom:14px}.admin-stat{background:#fff;border:1px solid rgba(15,23,42,.08);border-radius:15px;padding:12px;text-align:center}.admin-stat b{display:block;font-size:20px}.admin-stat span{font-size:10px;color:#64748b}.admin-filters{display:grid;grid-template-columns:1.5fr 1fr 1fr;gap:8px;margin-bottom:12px}.admin-filters input,.admin-filters select{width:100%;box-sizing:border-box;border:1px solid rgba(15,23,42,.12);border-radius:11px;padding:10px;background:#fff;font:600 11px Cairo,Arial,sans-serif}.admin-property-list{display:grid;gap:9px}.admin-property{background:#fff;border:1px solid rgba(15,23,42,.08);border-radius:16px;padding:10px}.admin-property-main{display:flex;gap:10px;align-items:center}.admin-property-thumb{width:72px;height:62px;border-radius:12px;background:#eef2f1 center/cover no-repeat;flex:none}.admin-property-info{min-width:0;flex:1}.admin-property-info h4{margin:0 0 4px;font-size:13px}.admin-property-info p{margin:2px 0;color:#64748b;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.admin-status{display:inline-flex;padding:3px 7px;border-radius:8px;font-size:9px;font-weight:800;background:#eef2f1}.admin-status.sold{background:#fff1f1;color:#a63a35}.admin-status.rented{background:#fff7e8;color:#9a6712}.admin-status.available{background:#eaf8f3;color:#087f68}.admin-property-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.admin-property-actions button{border:0;border-radius:9px;padding:7px 9px;font:800 9px Cairo,Arial,sans-serif;cursor:pointer}.admin-property-actions .manage{background:#edf4f2;color:#087f68}.admin-property-actions .sold{background:#fff1f1;color:#a63a35}.admin-property-actions .rent{background:#fff7e8;color:#9a6712}.admin-property-actions .delete{background:#fbe9e8;color:#a63a35}.admin-property-actions .restore{background:#eaf8f3;color:#087f68}.admin-empty{padding:22px;text-align:center;color:#64748b;font-size:11px}.admin-delete-action{width:100%;margin-top:8px;border:1px solid rgba(184,59,59,.15);border-radius:10px;background:#fff4f3;color:#a63a35;padding:8px 10px;font:800 9px Cairo,Arial,sans-serif;cursor:pointer}.admin-can-manage{outline:1px solid rgba(8,127,104,.10)}
  @media(max-width:700px){.admin-session-bar{top:8px;max-width:calc(100% - 16px);width:max-content}.admin-session-bar span{font-size:9px}.admin-session-bar button{padding:7px 8px;font-size:8px}.admin-stats{grid-template-columns:repeat(3,1fr)}.admin-filters{grid-template-columns:1fr}.admin-property-thumb{width:64px;height:56px}}
  `;document.head.appendChild(s)}
  function backToApp(){document.getElementById('adminPanel')?.classList.add('hidden');document.querySelector('.map-app')?.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>{window.formMap?.remove?.();window.formMap=null;window.MainGlobe?.getMap?.()?.invalidateSize?.()},150)}
  async function signOut(){await db.auth.signOut();document.getElementById('adminPanel')?.classList.add('hidden');document.querySelector('.map-app')?.classList.remove('hidden');removeAdminActions();showToast?.('تم تسجيل الخروج')}
  function removeAdminActions(){document.querySelectorAll('.admin-delete-action,.admin-session-bar').forEach(e=>e.remove())}
  function propertyFromListing(x){return x}
  async function adminSetStatus(id,status){if(!(await isAdmin()))return showToast?.('هذه العملية مخصصة للإدارة');const text=labels[status]||status;if(!confirm(`تغيير حالة الإعلان إلى «${text}»؟`))return;const {error}=await db.from('properties').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error){console.error(error);showToast?.('تعذر تحديث حالة الإعلان');return}showToast?.(`تم تحديث الحالة: ${text}`);await loadListings();renderDashboard()}
  async function deleteProperty(id,title){if(!(await isAdmin())){showToast?.('هذه العملية مخصصة للإدارة');return}if(!confirm(`حذف الإعلان «${title}» نهائياً؟\nسيختفي من الخريطة وقائمة العقارات.`))return;const {error}=await db.from('properties').delete().eq('id',id);if(error){console.error(error);showToast?.('تعذر حذف الإعلان. تحقق من صلاحيات الإدارة.');return}const {error:imgError}=await db.from('property_images').delete().eq('property_id',id);if(imgError)console.warn('property_images cleanup:',imgError);await loadListings();renderDashboard();showToast?.('تم حذف الإعلان')}
  function renderDashboard(){const root=document.getElementById('adminPropertyManager');if(!root)return;const q=(root.querySelector('#adminPropSearch')?.value||'').trim().toLocaleLowerCase('ar');const filter=root.querySelector('#adminStatusFilter')?.value||'all';const deal=root.querySelector('#adminDealFilter')?.value||'all';const items=data().filter(x=>(filter==='all'||((filter==='available'&&x.rawStatus==='published')||x.rawStatus===filter))&&(deal==='all'||x.deal===deal)&&(!q||`${x.title} ${x.location} ${x.type} ${x.details}`.toLocaleLowerCase('ar').includes(q)));const counts={all:data().length,published:data().filter(x=>x.rawStatus==='published').length,sold:data().filter(x=>x.rawStatus==='sold').length,rented:data().filter(x=>x.rawStatus==='rented').length,sale:data().filter(x=>x.deal==='sale').length};root.querySelector('#adminStatAll').textContent=counts.all;root.querySelector('#adminStatAvailable').textContent=counts.published;root.querySelector('#adminStatSale').textContent=counts.sale;root.querySelector('#adminStatSold').textContent=counts.sold;root.querySelector('#adminStatRented').textContent=counts.rented;const list=root.querySelector('#adminPropertyList');if(!items.length){list.innerHTML='<div class="admin-empty">لا توجد عقارات مطابقة.</div>';return}list.innerHTML=items.map(x=>{const status=x.rawStatus||'published';const img=x.image?`style="background-image:url('${esc(x.image)}')"`:'';return `<article class="admin-property"><div class="admin-property-main"><div class="admin-property-thumb" ${img}></div><div class="admin-property-info"><h4>${esc(x.title)}</h4><p>${esc(x.location)} · ${esc(typeLabels[x.type]||x.type||'عقار')}</p><p>${esc(x.price)}${x.deal==='rent'?' · شهرياً':''}</p><span class="admin-status ${statusClass[status]||''}">${esc(labels[status]||status)}</span></div></div><div class="admin-property-actions"><button class="manage" onclick="adminFocusProperty('${esc(x.id)}')">⌖ على الخريطة</button>${status!=='sold'?`<button class="sold" onclick="adminSetStatus('${esc(x.id)}','sold')">تم البيع</button>`:''}${status!=='rented'?`<button class="rent" onclick="adminSetStatus('${esc(x.id)}','rented')">تم التأجير</button>`:''}${status!=='published'?`<button class="restore" onclick="adminSetStatus('${esc(x.id)}','published')">إعادة متاح</button>`:''}<button class="delete" onclick="deleteProperty('${esc(x.id)}','${esc(x.title)}')">حذف</button></div></article>`}).join('')}
  function buildManager(){if(document.getElementById('adminPropertyManager'))return;const panel=document.getElementById('adminPanel');if(!panel)return;const container=panel.querySelector('.container');if(!container)return;const wrap=document.createElement('div');wrap.id='adminPropertyManager';wrap.className='admin-dashboard';wrap.innerHTML=`<div class="admin-card"><div class="admin-head"><div><span class="eyebrow">العقارات</span><h3>إدارة العقارات</h3><p>تحكم بحالة الإعلان بدون حذف بياناته.</p></div></div><div class="admin-stats"><div class="admin-stat"><b id="adminStatAll">0</b><span>كل العقارات</span></div><div class="admin-stat"><b id="adminStatAvailable">0</b><span>متاح</span></div><div class="admin-stat"><b id="adminStatSale">0</b><span>للبيع</span></div><div class="admin-stat"><b id="adminStatSold">0</b><span>مباع</span></div><div class="admin-stat"><b id="adminStatRented">0</b><span>مؤجّر</span></div></div><div class="admin-filters"><input id="adminPropSearch" type="search" placeholder="بحث بالعنوان أو المنطقة"><select id="adminStatusFilter"><option value="all">كل الحالات</option><option value="available">المتاحة</option><option value="sold">المباعة</option><option value="rented">المؤجرة</option></select><select id="adminDealFilter"><option value="all">كل العمليات</option><option value="sale">للبيع</option><option value="rent">للإيجار</option></select></div><div id="adminPropertyList" class="admin-property-list"></div></div>`;container.appendChild(wrap);wrap.querySelectorAll('input,select').forEach(el=>el.addEventListener('input',renderDashboard));renderDashboard()}
  function adminFocusProperty(id){const x=data().find(v=>v.id===id);if(!x)return;backToApp();setTimeout(()=>{window.MainGlobe?.focusProperty?.(id,x.latitude,x.longitude)},220)}
  function makeBar(){if(document.getElementById('adminSessionBar'))return;const bar=document.createElement('div');bar.id='adminSessionBar';bar.className='admin-session-bar';bar.innerHTML='<span><i></i> وضع الإدارة</span><button type="button" id="adminBackBtn">العودة للتطبيق</button><button type="button" id="adminLogoutBtn">تسجيل الخروج</button>';document.body.appendChild(bar);document.getElementById('adminBackBtn').onclick=backToApp;document.getElementById('adminLogoutBtn').onclick=signOut}
  function decorateCards(){document.querySelectorAll('.listing[data-property-id]').forEach(card=>{if(card.querySelector('.admin-delete-action'))return;const id=card.dataset.propertyId;const x=data().find(v=>v.id===id);if(!x)return;const body=card.querySelector('.listing-body');if(!body)return;const b=document.createElement('button');b.type='button';b.className='admin-delete-action';b.textContent='⌫ حذف الإعلان';b.onclick=e=>{e.stopPropagation();deleteProperty(x.id,x.title)};body.appendChild(b);card.classList.add('admin-can-manage')})}
  async function refreshAdminState(){const admin=await isAdmin();if(admin){makeBar();decorateCards();buildManager()}else removeAdminActions()}
  window.backToApp=backToApp;window.signOut=signOut;window.deleteProperty=deleteProperty;window.adminSetStatus=adminSetStatus;window.adminFocusProperty=adminFocusProperty;
  wait(()=>{installStyle();refreshAdminState();return !!document.body});
  db.auth.onAuthStateChange(()=>setTimeout(refreshAdminState,180));
  const observer=new MutationObserver(()=>{if(document.getElementById('adminSessionBar')){decorateCards();buildManager()}});wait(()=>{observer.observe(document.body,{childList:true,subtree:true});return true});
})();