/* لوحة الإدارة — الدفعة 3: تعديل العقارات ومراجعة الطلبات */
(function(){
  const wait=(fn,n=100)=>{if(fn())return;setTimeout(()=>wait(fn,n),n)};
  const escv=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const isAdmin=async()=>{try{const {data:{user}}=await db.auth.getUser();if(!user)return false;const {data:p}=await db.from('profiles').select('role').eq('id',user.id).single();return p?.role==='admin'}catch(_){return false}};
  const types={apartment:'شقة',house:'منزل',villa:'فيلا',land:'أرض',shop:'محل',office:'مكتب',building:'مبنى',other:'أخرى'};
  const deals={sale:'للبيع',rent:'للإيجار'};
  const statuses={published:'متاح',sold:'مباع',rented:'مؤجّر'};
  function style(){if(document.getElementById('adminBatch3Style'))return;const s=document.createElement('style');s.id='adminBatch3Style';s.textContent=`
  .a3-edit{background:#eef4ff!important;color:#285ea8!important}.a3-review{background:#f1ecff!important;color:#6546a5!important}.a3-modal-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.a3-modal-grid .full{grid-column:1/-1}.a3-modal-grid label{display:block;font:800 11px Cairo,sans-serif;color:#374151;margin:0 0 5px}.a3-modal-grid input,.a3-modal-grid select,.a3-modal-grid textarea{width:100%;box-sizing:border-box;border:1px solid #dce4e8;border-radius:12px;padding:10px;background:#fff;font:600 12px Cairo,sans-serif}.a3-modal-grid textarea{min-height:110px;resize:vertical}.a3-note{padding:10px 12px;border-radius:12px;background:#f7faf9;color:#64748b;font:600 10px/1.7 Cairo,sans-serif}.a3-actions{display:flex;gap:8px;margin-top:12px}.a3-actions button{flex:1;border:0;border-radius:11px;padding:10px;font:800 11px Cairo,sans-serif}.a3-submission{border:1px solid #e3e9eb;border-radius:14px;padding:11px;margin-bottom:9px;background:#fff}.a3-submission-head{display:flex;justify-content:space-between;gap:8px;align-items:start}.a3-submission b{font:900 13px Cairo,sans-serif}.a3-submission small,.a3-submission p{display:block;color:#64748b;font:600 10px/1.7 Cairo,sans-serif;margin:4px 0}.a3-status{display:inline-block;padding:3px 7px;border-radius:8px;background:#eef2f4;font:800 9px Cairo,sans-serif}.a3-status.pending{background:#fff7e8;color:#9a6712}.a3-status.approved{background:#eaf8f3;color:#087f68}.a3-status.rejected{background:#fff1f1;color:#a63a35}.a3-thumbs{display:flex;gap:6px;overflow:auto;margin-top:7px}.a3-thumbs img{width:64px;height:52px;object-fit:cover;border-radius:9px}.a3-sub-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.a3-sub-actions button{border:0;border-radius:9px;padding:7px 9px;font:800 9px Cairo,sans-serif}.a3-approve{background:#eaf8f3;color:#087f68}.a3-reject{background:#fff1f1;color:#a63a35}.a3-view{background:#edf4ff;color:#285ea8}@media(max-width:600px){.a3-modal-grid{grid-template-columns:1fr}.a3-modal-grid .full{grid-column:auto}}
  `;document.head.appendChild(s)}
  async function editProperty(id){
    if(!(await isAdmin()))return showToast?.('هذه العملية مخصصة للإدارة');
    const {data:x,error}=await db.from('properties').select('id,title,description,property_type,deal_type,price,area,rooms,address,latitude,longitude,status,owner_name,owner_phone').eq('id',id).single();
    if(error||!x)return showToast?.('تعذر تحميل بيانات العقار');
    const opts=(obj,val)=>Object.entries(obj).map(([k,v])=>`<option value="${k}" ${k===val?'selected':''}>${v}</option>`).join('');
    modal(`<h2>تعديل العقار</h2><p class="muted">عدّل البيانات الأساسية ثم احفظ. صلاحية التعديل محمية أيضاً بسياسات قاعدة البيانات.</p><form id="a3EditForm" class="a3-modal-grid"><div><label>عنوان الإعلان</label><input name="title" required value="${escv(x.title)}"></div><div><label>النوع</label><select name="property_type">${opts(types,x.property_type)}</select></div><div><label>العملية</label><select name="deal_type">${opts(deals,x.deal_type)}</select></div><div><label>الحالة</label><select name="status">${opts(statuses,x.status)}</select></div><div><label>السعر</label><input name="price" type="number" min="0" value="${escv(x.price)}"></div><div><label>المساحة م²</label><input name="area" type="number" min="0" value="${escv(x.area)}"></div><div><label>الغرف</label><input name="rooms" type="number" min="0" value="${escv(x.rooms)}"></div><div><label>العنوان / المنطقة</label><input name="address" value="${escv(x.address)}"></div><div><label>اسم المالك</label><input name="owner_name" value="${escv(x.owner_name)}"></div><div><label>هاتف المالك</label><input name="owner_phone" value="${escv(x.owner_phone)}"></div><div><label>خط العرض</label><input name="latitude" type="number" step="any" value="${escv(x.latitude)}"></div><div><label>خط الطول</label><input name="longitude" type="number" step="any" value="${escv(x.longitude)}"></div><div class="full"><label>التفاصيل</label><textarea name="description">${escv(x.description)}</textarea></div><div class="full a3-note">تعديل البيانات لا يغيّر الصور الموجودة. الصور تبقى مرتبطة بالعقار كما هي.</div><div class="full a3-actions"><button type="button" class="ghost" onclick="closeModal()">إلغاء</button><button class="primary">حفظ التعديلات</button></div></form>`);
    document.getElementById('a3EditForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),button=e.target.querySelector('button.primary');button.disabled=true;const n=k=>{const v=f.get(k);return v===''?null:v};const patch={title:n('title'),description:n('description'),property_type:n('property_type'),deal_type:n('deal_type'),price:n('price'),area:n('area'),rooms:n('rooms'),address:n('address'),owner_name:n('owner_name'),owner_phone:n('owner_phone'),latitude:n('latitude'),longitude:n('longitude'),status:n('status'),updated_at:new Date().toISOString()};const {error}=await db.from('properties').update(patch).eq('id',id);if(error){button.disabled=false;console.error(error);showToast?.('تعذر حفظ التعديلات');return}closeModal();showToast?.('تم حفظ تعديلات العقار');await loadListings();window.renderDashboard?.()};
  }
  async function reviewSubmission(id){
    if(!(await isAdmin()))return showToast?.('هذه العملية مخصصة للإدارة');
    const {data:s,error}=await db.from('property_submissions').select('*').eq('id',id).single();if(error||!s)return showToast?.('تعذر تحميل الطلب');
    const imgs=(s.image_urls||[]).map(u=>`<img src="${escv(u)}" alt="صورة العقار" loading="lazy">`).join('');
    modal(`<h2>مراجعة طلب الإعلان</h2><div class="a3-submission"><div class="a3-submission-head"><b>${escv(s.title)}</b><span class="a3-status ${escv(s.status)}">${escv(s.status)}</span></div><p>المرسل: ${escv(s.submitter_name)} · ${escv(s.submitter_phone)}</p><p>${escv(types[s.property_type]||s.property_type)} · ${escv(deals[s.deal_type]||s.deal_type)} · ${escv(s.address||'')}</p><p>السعر: ${escv(s.price??'عند التواصل')} · المساحة: ${escv(s.area??'—')} · الغرف: ${escv(s.rooms??'—')}</p><p>${escv(s.description||'لا يوجد وصف')}</p><div class="a3-thumbs">${imgs||'<small>لا توجد صور</small>'}</div></div><div class="a3-note">الموافقة تنشئ عقاراً منشوراً. إذا كانت البيانات غير مناسبة يمكنك رفض الطلب مع كتابة سبب، من دون كشف ملاحظات الإدارة للزوار.</div><div class="a3-actions"><button class="ghost" onclick="closeModal()">إغلاق</button>${s.status==='pending'?`<button class="a3-reject" onclick="rejectSubmission('${escv(s.id)}');closeModal()">رفض</button><button class="a3-approve" onclick="approveSubmission('${escv(s.id)}');closeModal()">موافقة ونشر</button>`:''}</div>`);
  }
  function addEditButtons(){const root=document.getElementById('adminPropertyManager');if(!root)return;root.querySelectorAll('.admin-property').forEach(card=>{if(card.querySelector('.a3-edit'))return;const id=card.querySelector('button.manage')?.getAttribute('onclick')?.match(/'([^']+)'/)?.[1];if(!id)return;const actions=card.querySelector('.admin-property-actions');const b=document.createElement('button');b.className='a3-edit';b.textContent='✎ تعديل';b.onclick=()=>editProperty(id);actions?.insertBefore(b,actions.firstChild)})}
  function enhanceSubmissions(){const box=document.getElementById('submissionList');if(!box||box.dataset.a3==='1')return;box.dataset.a3='1';const observer=new MutationObserver(()=>{box.querySelectorAll('.submission').forEach(row=>{if(row.querySelector('.a3-review'))return;const id=row.querySelector('button[onclick*="approveSubmission"]')?.getAttribute('onclick')?.match(/'([^']+)'/)?.[1];if(!id)return;const b=document.createElement('button');b.className='a3-review';b.textContent='👁 مراجعة';b.onclick=()=>reviewSubmission(id);row.querySelector('.submission-actions')?.appendChild(b)})});observer.observe(box,{childList:true,subtree:true})}
  function expose(){window.editProperty=editProperty;window.reviewSubmission=reviewSubmission;addEditButtons();enhanceSubmissions();return !!document.body}
  style();wait(expose);setInterval(()=>{if(document.getElementById('adminSessionBar')){addEditButtons();enhanceSubmissions()}},900);
})();
