// Akarat frontend: Supabase listings, public submission form, admin-only dashboard.
const SUPABASE_URL='https://utvwvwlrsqoccqwxgfil.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_bR3lG3PwdaX3XSyo6s3_uQ_25LWaOCC';
const {createClient}=supabase; const db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
let listings=[]; let publicMap=null; let publicMarkers=null;
const labels={rent:'للإيجار',sale:'للبيع'}; const typeLabels={apartment:'شقة',house:'منزل',villa:'فيلا',land:'أرض',shop:'محل',office:'مكتب',building:'مبنى',other:'أخرى'};
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const price=v=>v==null||v===''?'السعر عند التواصل':`${Number(v).toLocaleString('ar-SY')} ل.س`;
const details=x=>[x.rooms!=null?`${x.rooms} غرف`:'',x.area!=null?`${Number(x.area).toLocaleString('ar-SY')} م²`:'' ].filter(Boolean).join(' · ')||'التفاصيل متوفرة داخل الإعلان';
function normalize(x){const ims=(x.property_images||[]).slice().sort((a,b)=>a.sort_order-b.sort_order);return {id:x.id,deal:x.deal_type,type:x.property_type,title:x.title,location:x.address||'الموقع عند التواصل',details:details(x),price:price(x.price),image:ims[0]?.image_url||'',latitude:x.latitude,longitude:x.longitude,images:ims}}
async function loadListings(){const s=document.getElementById('listingStatus');try{const {data,error}=await db.from('properties').select('id,title,description,property_type,deal_type,price,area,rooms,address,latitude,longitude,status,property_images(id,image_url,sort_order)').in('status',['published','sold','rented']).order('created_at',{ascending:false});if(error)throw error;listings=(data||[]).map(normalize);s.classList.add('hidden');render();drawPublicMap()}catch(e){console.error(e);s.textContent='تعذر تحميل العقارات حالياً.'}}
function render(items=listings){const g=document.getElementById('listingGrid'),e=document.getElementById('emptyState');g.innerHTML=items.map(x=>`<article class="listing"><div class="listing-img" ${x.image?`style="background-image:url('${esc(x.image)}')"`:''}><span class="badge">${esc(labels[x.deal]||x.deal)}</span></div><div class="listing-body"><h3>${esc(x.title)}</h3><div class="meta">📍 ${esc(x.location)}</div><div class="meta">${esc(typeLabels[x.type]||x.type)} · ${esc(x.details)}</div><div class="price">${esc(x.price)} <small>${x.deal==='rent'?'شهرياً':''}</small></div></div></article>`).join('');e.classList.toggle('hidden',items.length>0)}
function filterListings(){const q=document.getElementById('searchInput').value.trim().toLowerCase(),d=document.getElementById('dealFilter').value,t=document.getElementById('typeFilter').value;render(listings.filter(x=>(d==='all'||x.deal===d)&&(t==='all'||x.type===t)&&(!q||`${x.title} ${x.location} ${x.details} ${typeLabels[x.type]||''}`.toLowerCase().includes(q))))}
function resetFilters(){document.getElementById('searchInput').value='';document.getElementById('dealFilter').value='all';document.getElementById('typeFilter').value='all';document.querySelectorAll('.category').forEach(c=>c.classList.remove('active'));document.querySelector('.chip[data-deal="all"]')?.classList.add('active');render();drawPublicMap()}
function showToast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),3000)}
function modal(html){let m=document.getElementById('appModal');if(!m){m=document.createElement('div');m.id='appModal';m.className='modal';document.body.appendChild(m)}m.innerHTML=`<div class="modal-card"><button class="modal-close" onclick="closeModal()">×</button>${html}</div>`;m.classList.remove('hidden')}
function closeModal(){document.getElementById('appModal')?.classList.add('hidden');setTimeout(()=>window.formMap?.remove(),100)}
function initPickerMap(containerId,latInputId,lngInputId){const lat=Number(document.getElementById(latInputId)?.value)||34.73,lng=Number(document.getElementById(lngInputId)?.value)||36.72;const map=L.map(containerId).setView([lat,lng],latInputId==='subLat'?12:13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);let marker=null;const place=(a,b)=>{document.getElementById(latInputId).value=a.toFixed(6);document.getElementById(lngInputId).value=b.toFixed(6);if(marker)marker.setLatLng([a,b]);else marker=L.marker([a,b]).addTo(map);};if(document.getElementById(latInputId).value)place(lat,lng);map.on('click',e=>place(e.latlng.lat,e.latlng.lng));setTimeout(()=>map.invalidateSize(),150);return map}
function drawPublicMap(){if(!window.L||!document.getElementById('publicMap'))return;if(!publicMap){publicMap=L.map('publicMap',{zoomControl:false}).setView([34.73,36.72],8);L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri'}).addTo(publicMap);publicMarkers=L.layerGroup().addTo(publicMap);document.getElementById('zoomIn')?.addEventListener('click',()=>publicMap.zoomIn());document.getElementById('zoomOut')?.addEventListener('click',()=>publicMap.zoomOut());document.getElementById('resetMap')?.addEventListener('click',()=>publicMap.setView([34.73,36.72],8));document.getElementById('locateBtn')?.addEventListener('click',()=>publicMap.locate({setView:true,maxZoom:15,enableHighAccuracy:true}));}publicMarkers.clearLayers();const counts={all:listings.length,sale:listings.filter(x=>x.deal==='sale').length,rent:listings.filter(x=>x.deal==='rent').length,land:listings.filter(x=>x.type==='land').length};Object.entries(counts).forEach(([k,v])=>{const el=document.getElementById('count'+k.charAt(0).toUpperCase()+k.slice(1));if(el)el.textContent=v});const withCoords=listings.filter(x=>Number.isFinite(Number(x.latitude))&&Number.isFinite(Number(x.longitude)));withCoords.forEach(x=>{const cls=x.deal==='rent'?'rent':'sale';const label=x.price==='السعر عند التواصل'?'تواصل':x.price.replace(' ل.س','');const icon=L.divIcon({className:'',html:'<div class="price-marker '+cls+'"><span>'+esc(label)+' 🏠</span></div>',iconSize:[100,50],iconAnchor:[50,50]});L.marker([x.latitude,x.longitude],{icon}).addTo(publicMarkers).bindPopup('<div dir="rtl"><b>'+esc(x.title)+'</b><br>'+esc(x.price)+'<br>'+esc(x.location)+'</div>')});if(withCoords.length)publicMap.fitBounds(withCoords.map(x=>[x.latitude,x.longitude]),{padding:[35,35],maxZoom:14});setTimeout(()=>publicMap.invalidateSize(),100)}
async function uploadImages(files,folder){const urls=[];for(const file of Array.from(files||[])){if(!file.type.startsWith('image/'))throw new Error('يسمح برفع الصور فقط');if(file.size>8*1024*1024)throw new Error('حجم الصورة يجب ألا يتجاوز 8 ميغابايت');const safe=file.name.replace(/[^\w.\-\u0600-\u06ff ]/g,'_');const path=`${folder}/${crypto.randomUUID()}-${safe}`;const {error}=await db.storage.from('property-images').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(error)throw error;urls.push(db.storage.from('property-images').getPublicUrl(path).data.publicUrl)}return urls}
function imageInput(name){return `<div class="file-field"><label>صور العقار</label><input name="${name}" type="file" accept="image/jpeg,image/png,image/webp" multiple><small>حتى 8 ميغابايت للصورة، ويمكن اختيار عدة صور.</small></div>`}
function locationPickerHtml(prefix){return `<div class="location-box"><label>موقع العقار على الخريطة</label><div id="${prefix}Map" class="picker-map"></div><small>اضغط على الخريطة لوضع العلامة، ويمكنك تحريك الخريطة قبل اختيار النقطة.</small><div class="coords"><input id="${prefix}Lat" name="latitude" type="number" step="any" placeholder="خط العرض" readonly><input id="${prefix}Lng" name="longitude" type="number" step="any" placeholder="خط الطول" readonly></div></div>`}
function publicLoginMessage(){openLogin()}
function openLogin(){modal(`<h2>تسجيل الدخول / إنشاء حساب</h2><p class="muted">يمكنك إدخال بريدك وكلمة المرور. الوصول إلى لوحة الإدارة مخصص للحساب الإداري فقط.</p><div style="display:flex;gap:8px;margin:12px 0"><button type="button" class="ghost" id="loginTab">تسجيل الدخول</button><button type="button" class="ghost" id="signupTab">إنشاء حساب</button></div><form id="loginForm" class="form-grid"><input name="email" type="email" placeholder="البريد الإلكتروني" required><input name="password" type="password" placeholder="كلمة المرور" minlength="6" required><button class="primary">تسجيل الدخول</button></form><form id="signupForm" class="form-grid hidden"><input name="email" type="email" placeholder="البريد الإلكتروني" required><input name="password" type="password" placeholder="كلمة المرور (6 أحرف على الأقل)" minlength="6" required><button class="primary">إنشاء حساب</button></form>`);const lf=document.getElementById('loginForm'),sf=document.getElementById('signupForm');document.getElementById('loginTab').onclick=()=>{lf.classList.remove('hidden');sf.classList.add('hidden')};document.getElementById('signupTab').onclick=()=>{sf.classList.remove('hidden');lf.classList.add('hidden')};lf.onsubmit=login;sf.onsubmit=signup}
async function login(e){e.preventDefault();const f=new FormData(e.target);const {error}=await db.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error){showToast('تسجيل الدخول أو إنشاء الحساب سيتوفر قريباً');return}const ok=await checkAdmin();if(ok)closeModal()}
async function signup(e){e.preventDefault();const f=new FormData(e.target);const {data,error}=await db.auth.signUp({email:f.get('email'),password:f.get('password')});if(error){showToast('تسجيل الدخول أو إنشاء الحساب سيتوفر قريباً');return}if(data?.user){await db.auth.signOut()}showToast('تسجيل الدخول أو إنشاء الحساب سيتوفر قريباً')}
async function checkAdmin(){const {data:{user}}=await db.auth.getUser();if(!user)return false;const {data:p,error}=await db.from('profiles').select('role').eq('id',user.id).single();if(error||p?.role!=='admin'){await db.auth.signOut();showToast('تسجيل الدخول أو إنشاء الحساب سيتوفر قريباً');return false}showAdmin();return true}
function showAdmin(){let panel=document.getElementById('adminPanel');if(!panel){panel=document.createElement('section');panel.id='adminPanel';panel.className='admin-section';panel.innerHTML=`<div class="container"><div class="admin-head"><div><span class="eyebrow">إدارة خاصة</span><h2>لوحة الإدارة</h2><p>طلبات الزوار لا تصبح منشورة إلا بموافقتك.</p></div><div><button class="ghost" onclick="backToApp()">العودة للموقع</button> <button class="ghost" onclick="signOut()">تسجيل الخروج</button></div></div><div class="admin-grid"><div class="admin-card"><h3>طلبات الإعلانات</h3><div id="submissionList">جاري التحميل...</div></div><div class="admin-card"><h3>إضافة عقار مباشرة</h3><p class="muted">أضف الصور وحدد الموقع على الخريطة، ثم ينشر العقار مباشرة باسم الإدارة.</p><form id="adminPropertyForm" class="form-grid"><input name="title" placeholder="عنوان الإعلان" required><select name="property_type"><option value="apartment">شقة</option><option value="house">منزل</option><option value="villa">فيلا</option><option value="land">أرض</option><option value="shop">محل</option><option value="office">مكتب</option><option value="building">مبنى</option><option value="other">أخرى</option></select><select name="deal_type"><option value="sale">للبيع</option><option value="rent">للإيجار</option></select><input name="price" type="number" min="0" placeholder="السعر"><input name="area" type="number" min="0" placeholder="المساحة م²"><input name="rooms" type="number" min="0" placeholder="عدد الغرف"><input name="address" placeholder="العنوان"><input name="owner_name" placeholder="اسم المالك"><input name="owner_phone" placeholder="هاتف المالك">${locationPickerHtml('admin')}<div class="full">${imageInput('images')}</div><textarea name="description" placeholder="تفاصيل الإعلان"></textarea><button class="primary">نشر العقار</button></form></div></div></div>`;document.body.appendChild(panel);document.getElementById('adminPropertyForm').onsubmit=adminAdd}panel.classList.remove('hidden');loadSubmissions();setTimeout(()=>{window.formMap=initPickerMap('adminMap','adminLat','adminLng')},120);panel.scrollIntoView({behavior:'smooth'})}
async function loadSubmissions(){const box=document.getElementById('submissionList');const {data,error}=await db.from('property_submissions').select('*').order('created_at',{ascending:false});if(error){box.textContent='تعذر تحميل الطلبات.';return}if(!data?.length){box.innerHTML='<div class="empty">لا توجد طلبات حالياً.</div>';return}box.innerHTML=data.map(s=>`<div class="submission"><b>${esc(s.title)}</b><span>${esc(typeLabels[s.property_type]||s.property_type)} · ${esc(labels[s.deal_type]||s.deal_type)} · ${esc(s.submitter_name)} · ${esc(s.submitter_phone)}</span><small>${esc(s.address||'')}</small>${(s.image_urls||[]).length?`<div class="thumbs">${s.image_urls.map(u=>`<img src="${esc(u)}" alt="صورة العقار">`).join('')}</div>`:''}<div class="submission-actions">${s.status==='pending'?`<button class="primary" onclick="approveSubmission('${s.id}')">موافقة ونشر</button><button class="danger" onclick="rejectSubmission('${s.id}')">رفض</button>`:`<span>الحالة: ${esc(s.status)}</span>`}</div></div>`).join('')}
async function approveSubmission(id){const {data:s,error}=await db.from('property_submissions').select('*').eq('id',id).single();if(error||!s)return showToast('تعذر قراءة الطلب');const {data:{user}}=await db.auth.getUser();const {data:p,error:e}=await db.from('properties').insert({title:s.title,description:s.description,property_type:s.property_type,deal_type:s.deal_type,price:s.price,area:s.area,rooms:s.rooms,address:s.address,latitude:s.latitude,longitude:s.longitude,owner_name:s.owner_name,owner_phone:s.owner_phone,status:'published',published_at:new Date().toISOString(),created_by:user.id}).select('id').single();if(e)return showToast('تعذر نشر الإعلان');if(s.image_urls?.length){const rows=s.image_urls.map((u,i)=>({property_id:p.id,image_url:u,sort_order:i}));const {error:ie}=await db.from('property_images').insert(rows);if(ie)return showToast('تم إنشاء الإعلان لكن تعذر ربط الصور');}await db.from('property_submissions').update({status:'approved',reviewed_at:new Date().toISOString(),reviewed_by:user.id}).eq('id',id);showToast('تم نشر الإعلان مع الصور');loadSubmissions();loadListings()}
async function rejectSubmission(id){const {data:{user}}=await db.auth.getUser();const reason=prompt('سبب الرفض (اختياري):')||null;const {error}=await db.from('property_submissions').update({status:'rejected',admin_note:reason,reviewed_at:new Date().toISOString(),reviewed_by:user.id}).eq('id',id);showToast(error?'تعذر رفض الطلب':'تم رفض الطلب');loadSubmissions()}
async function adminAdd(e){e.preventDefault();const f=new FormData(e.target);const {data:{user}}=await db.auth.getUser();const row=Object.fromEntries(f.entries());const files=f.getAll('images');delete row.images;['price','area','rooms','latitude','longitude'].forEach(k=>{row[k]=row[k]?Number(row[k]):null});Object.assign(row,{status:'published',published_at:new Date().toISOString(),created_by:user.id});try{const {data:p,error}=await db.from('properties').insert(row).select('id').single();if(error)throw error;if(files.length){const urls=await uploadImages(files,`properties/${p.id}`);const {error:ie}=await db.from('property_images').insert(urls.map((u,i)=>({property_id:p.id,image_url:u,sort_order:i})));if(ie)throw ie}showToast('تم نشر العقار مع الصور');e.target.reset();loadListings();window.formMap?.remove();window.formMap=initPickerMap('adminMap','adminLat','adminLng')}catch(err){console.error(err);showToast(err.message||'تعذر نشر العقار')}}
async function backToApp(){document.getElementById('adminPanel')?.classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'',location.pathname+location.search)}
async function signOut(){await db.auth.signOut();document.getElementById('adminPanel')?.classList.add('hidden');showToast('تم تسجيل الخروج')}
function openSubmission(){modal(`<h2>إضافة إعلان</h2><p class="muted">أرسل بيانات العقار مع الصور وحدد موقعه على الخريطة. سيصل الطلب إلى الإدارة، ولن يظهر للعامة قبل موافقتك.</p><form id="submissionForm" class="form-grid"><input name="submitter_name" placeholder="اسمك" required><input name="submitter_phone" placeholder="رقم هاتفك" required><input name="title" placeholder="عنوان الإعلان" required><select name="property_type"><option value="apartment">شقة</option><option value="house">منزل</option><option value="villa">فيلا</option><option value="land">أرض</option><option value="shop">محل</option><option value="office">مكتب</option><option value="building">مبنى</option><option value="other">أخرى</option></select><select name="deal_type"><option value="sale">للبيع</option><option value="rent">للإيجار</option></select><input name="price" type="number" min="0" placeholder="السعر"><input name="area" type="number" min="0" placeholder="المساحة م²"><input name="rooms" type="number" min="0" placeholder="عدد الغرف"><input name="address" placeholder="العنوان"><input name="owner_name" placeholder="اسم المالك"><input name="owner_phone" placeholder="هاتف المالك">${locationPickerHtml('sub')}<div class="full">${imageInput('images')}</div><textarea name="description" placeholder="تفاصيل العقار"></textarea><button class="primary">إرسال الطلب</button></form>`);document.getElementById('submissionForm').onsubmit=submitProperty;setTimeout(()=>{window.formMap=initPickerMap('subMap','subLat','subLng')},120)}
async function submitProperty(e){e.preventDefault();const f=new FormData(e.target),row=Object.fromEntries(f.entries());const files=f.getAll('images');delete row.images;['price','area','rooms','latitude','longitude'].forEach(k=>{row[k]=row[k]?Number(row[k]):null});try{let imageUrls=[];if(files.length)imageUrls=await uploadImages(files,`submissions/${crypto.randomUUID()}`);row.image_urls=imageUrls;row.status='pending';const {error}=await db.from('property_submissions').insert(row);if(error)throw error;closeModal();showToast('تم إرسال الإعلان والصور، وسيبقى قيد المراجعة حتى موافقة الإدارة')}catch(err){console.error(err);showToast(err.message||'تعذر إرسال الطلب حالياً')}}
document.querySelector('.add-btn')?.addEventListener('click',openSubmission);document.querySelectorAll('.category').forEach(c=>c.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');document.getElementById('dealFilter').value=c.dataset.deal;filterListings()}));document.getElementById('searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')filterListings()});
const adminBtn=document.createElement('button');adminBtn.className='login-btn';adminBtn.textContent='دخول الإدارة';adminBtn.onclick=openLogin;document.querySelector('.nav')?.appendChild(adminBtn);
loadListings();
// Public users never see an admin login. The private entry is intentionally not linked in the public UI.
if(location.hash==='#office'){openLogin()}
db.auth.onAuthStateChange((event)=>{if(event==='SIGNED_IN')checkAdmin()});
function toggleMenu(){document.getElementById('sideMenu')?.classList.toggle('hidden')}
