/* مكتب المجد العقاري: local assistant layer */
(function(){
  const state={open:false,visible:true,knowledge:'',dragging:false};
  const norm=s=>String(s||'').toLowerCase().replace(/[إأآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').trim();
  const data=()=>typeof listings!=='undefined'?(listings||[]):[];
  const money=s=>{const m=norm(s).match(/(?:تحت|اقل من|أقل من|حد|بحدود|الى|إلى|حتى)\s*([\d.,]+)\s*(مليون|م|الف|ألف|ل\.س|ليرة)?/);if(!m)return null;let n=Number(m[1].replace(/[,.]/g,''));if(m[2]&&m[2].includes('مليون'))n*=1000000;else if(m[2]&&m[2].includes('الف'))n*=1000;return n};
  const typeMap={شقة:'apartment',شقق:'apartment',منزل:'house',بيت:'house',فيلا:'villa',أرض:'land',اراضي:'land',محل:'shop',مكتب:'office',مبنى:'building'};
  function parse(q){const s=norm(q);let deal=null,type=null,max=money(q),min=null;for(const k in typeMap)if(s.includes(norm(k))){type=typeMap[k];break}if(/ايجار|إيجار|للايجار|للإيجار|استئجار/.test(s))deal='rent';if(/بيع|للبيع|شراء/.test(s))deal='sale';const mm=s.match(/(?:فوق|اكثر من|أكثر من)\s*([\d.,]+)\s*(مليون|م|الف|ألف)?/);if(mm){min=Number(mm[1].replace(/[,.]/g,''));if(mm[2]&&mm[2].includes('مليون'))min*=1000000;else if(mm[2]&&mm[2].includes('الف'))min*=1000}return {deal,type,min,max};}
  function numericPrice(x){const n=String(x.price||'').replace(/[^\d]/g,'');return n?Number(n):null}
  function filter(q){const p=parse(q);return data().filter(x=>(!p.deal||x.deal===p.deal)&&(!p.type||x.type===p.type)&&(!p.max||numericPrice(x)==null||numericPrice(x)<=p.max)&&(!p.min||numericPrice(x)==null||numericPrice(x)>=p.min));}
  function card(x){return `<div class="ai-result"><b>${esc(x.title)}</b><span>📍 ${esc(x.location)}</span><span>💰 ${esc(x.price)}</span><span>${esc(typeLabels[x.type]||x.type)} · ${esc(x.details)}</span></div>`}
  function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
  function answer(q){const all=data(),s=norm(q);if(!all.length)return 'لسا ما في عقارات منشورة بالبيانات الحالية.';const results=filter(q);if(/قارن|مقارن|قارني/.test(s)&&results.length){const sorted=[...results].sort((a,b)=>(numericPrice(a)||Infinity)-(numericPrice(b)||Infinity));return `وجدت ${results.length} عقار مناسب للمقارنة:<div class="ai-results">${sorted.slice(0,5).map(card).join('')}</div>`}if(/ارخص|أرخص/.test(s)){const r=results.filter(x=>numericPrice(x)!=null).sort((a,b)=>numericPrice(a)-numericPrice(b));return r.length?`أرخص خيار ضمن النتائج هو:<div class="ai-results">${card(r[0])}</div>`:'ما لقيت سعراً رقمياً مناسباً ضمن النتائج.'}if(/اغلى|أغلى|اعلى سعر|أعلى سعر/.test(s)){const r=results.filter(x=>numericPrice(x)!=null).sort((a,b)=>numericPrice(b)-numericPrice(a));return r.length?`أعلى سعر ضمن النتائج:<div class="ai-results">${card(r[0])}</div>`:'ما لقيت سعراً رقمياً مناسباً ضمن النتائج.'}if(!results.length)return 'ما لقيت عقارات تطابق طلبك حالياً. جرّب تغيير السعر أو نوع العقار أو البيع/الإيجار.';return `لقيت ${results.length} عقار مناسب لطلبك:<div class="ai-results">${results.slice(0,5).map(card).join('')}</div>`}
  function add(msg,who){const box=document.getElementById('aiMessages');if(!box)return;const el=document.createElement('div');el.className='ai-msg '+who;el.innerHTML=msg;box.appendChild(el);box.scrollTop=box.scrollHeight}
  function send(){const input=document.getElementById('aiInput');const q=input.value.trim();if(!q)return;add(esc(q),'user');input.value='';setTimeout(()=>add(answer(q),'bot'),80)}
  function open(){state.visible=true;state.open=true;document.getElementById('aiPanel')?.classList.remove('hidden')}
  function build(){if(document.getElementById('aiPanel'))return;const panel=document.createElement('section');panel.id='aiPanel';panel.className='ai-panel hidden';panel.innerHTML=`<header><div><b>مساعد مكتب المجد العقاري</b><small>يفهم العقارات الموجودة على الخريطة</small></div><button id="aiClose">×</button></header><div id="aiMessages" class="ai-messages"><div class="ai-msg bot">أهلاً 👋<br>أنا مساعد مكتب المجد العقاري. اسألني عن العقارات المنشورة، السعر، البيع أو الإيجار، أو اطلب مني المقارنة.</div></div><div class="ai-suggestions"><button>شقق للإيجار</button><button>أرخص عقار</button><button>قارن العقارات</button></div><footer><input id="aiInput" placeholder="مثلاً: شقة للإيجار تحت 5 مليون"><button id="aiSend">إرسال</button></footer>`;document.body.appendChild(panel);document.getElementById('aiClose').onclick=()=>{state.open=false;panel.classList.add('hidden')};document.getElementById('aiSend').onclick=send;document.getElementById('aiInput').addEventListener('keydown',e=>{if(e.key==='Enter')send()});panel.querySelectorAll('.ai-suggestions button').forEach(b=>b.onclick=()=>{document.getElementById('aiInput').value=b.textContent;send()})}
  async function loadKnowledge(){try{state.knowledge=await fetch('knowledge/assistant.md').then(r=>r.ok?r.text():'')}catch(_){} }
  window.openAssistant=open;window.hideAssistant=()=>{state.open=false;document.getElementById('aiPanel')?.classList.add('hidden')};window.AkaratAssistant={answer,loadKnowledge,open};build();loadKnowledge();
})();