(()=>{
  const MAP_ID='publicMap';
  const CENTER=[38.5,35.1];
  const SYRIA_BOUNDS=[[32.0,35.4],[37.6,42.7]];
  const style={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,maxzoom:19,attribution:'© OpenStreetMap contributors'},satellite:{type:'raster',tiles:['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:19,attribution:'Tiles © Esri'}},layers:[{id:'base',type:'raster',source:'osm'}]};
  let map=null;
  let markerLayer=[];
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const money=v=>v==null||v===''?'السعر عند التواصل':`${Number(v).toLocaleString('ar-SY')} ل.س`;
  function inject(){if(document.getElementById('mainMapCss'))return;const s=document.createElement('style');s.id='mainMapCss';s.textContent=`#publicMap{background:#dfe6e3;overflow:hidden}.leaflet-container{display:none!important}.main-map-shell{position:absolute;inset:0;z-index:2}.main-map-shell .maplibregl-canvas{outline:none}.main-map-shell .maplibregl-ctrl-group{background:rgba(255,255,255,.9);backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);border:1px solid rgba(16,24,40,.1);border-radius:15px;overflow:hidden;box-shadow:0 8px 22px rgba(16,24,40,.14)}.main-map-shell .maplibregl-ctrl button{width:42px;height:42px}.map-syria-label{position:absolute;right:18px;bottom:calc(34dvh + 25px);z-index:5;padding:7px 11px;border-radius:999px;background:rgba(255,255,255,.86);color:#344054;font:700 10px Cairo,Arial,sans-serif;box-shadow:0 6px 18px rgba(16,24,40,.1);pointer-events:none;backdrop-filter:blur(12px)}`;document.head.appendChild(s)}
  function create(){if(!window.maplibregl||!document.getElementById(MAP_ID))return false;if(map)return true;inject();const host=document.getElementById(MAP_ID);host.querySelectorAll('.leaflet-pane,.leaflet-control-container,.leaflet-marker-icon,.leaflet-marker-shadow').forEach(x=>x.remove());const shell=document.createElement('div');shell.className='main-map-shell';host.appendChild(shell);map=new maplibregl.Map({container:shell,style,center:CENTER,zoom:5.45,minZoom:5,maxZoom:18,maxBounds:[[32.0,35.4],[37.6,42.7]],maxBoundsViscosity:1,projection:{type:'mercator'},pitch:0,dragRotate:false,renderWorldCopies:false,attributionControl:false});map.addControl(new maplibregl.NavigationControl({showCompass:false}), 'bottom-left');map.addControl(new maplibregl.AttributionControl({compact:true}));const tag=document.createElement('div');tag.className='map-syria-label';tag.textContent='سورية';shell.appendChild(tag);map.on('load',()=>{setTimeout(()=>map.resize(),80);loadPins();});return true}
  async function loadPins(){if(!map||!window.db)return;markerLayer.forEach(m=>m.remove());markerLayer=[];const {data,error}=await db.from('properties').select('id,title,price,address,latitude,longitude,status').in('status',['published','sold','rented']).not('latitude','is',null).not('longitude','is',null);if(error)return;(data||[]).forEach(x=>{const el=document.createElement('div');el.className='globe-pin';el.innerHTML='<span>⌂</span>';const popup=new maplibregl.Popup({offset:20,closeButton:true}).setHTML(`<div class="globe-popup"><b>${esc(x.title)}</b><div>${esc(money(x.price))}</div><small>${esc(x.address||'الموقع عند التواصل')}</small></div>`);const m=new maplibregl.Marker({element:el,anchor:'bottom'}).setLngLat([Number(x.longitude),Number(x.latitude)]).setPopup(popup).addTo(map);markerLayer.push(m)});}
  function wire(){document.getElementById('zoomIn')?.addEventListener('click',()=>map?.zoomIn());document.getElementById('zoomOut')?.addEventListener('click',()=>map?.zoomOut());document.getElementById('resetMap')?.addEventListener('click',()=>map?.fitBounds([[35.4,32.0],[42.7,37.6]],{padding:55,duration:850}));document.getElementById('locateBtn')?.addEventListener('click',()=>{if(!map||!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(p=>map.flyTo({center:[p.coords.longitude,p.coords.latitude],zoom:11,duration:1200}),()=>{});});}
  function boot(){if(!create()){setTimeout(boot,300);return}wire();}
  new MutationObserver(()=>{if(!map)boot()}).observe(document.body,{childList:true,subtree:true});
  setTimeout(boot,250);
  window.MainGlobe={reload:loadPins,focus:(lng,lat,z=11)=>map?.flyTo({center:[lng,lat],zoom:z,duration:900})};
})();