(()=>{
  const MAP_ID='publicMap';
  const CENTER=[35.1,38.5];
  const BOUNDS=[[32.0,35.4],[37.6,42.7]];
  let map=null, markers=null;
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const money=v=>v==null||v===''?'تواصل للسعر':`${Number(v).toLocaleString('ar-SY')} ل.س`;
  function inject(){if(document.getElementById('mainMapCss'))return;const s=document.createElement('style');s.id='mainMapCss';s.textContent=`#publicMap{background:#e7ecea;overflow:hidden}.main-leaflet{position:absolute;inset:0;z-index:2}.main-leaflet .leaflet-control-zoom{border:0!important;box-shadow:0 8px 22px rgba(16,24,40,.14)!important}.main-leaflet .leaflet-control-zoom a{width:42px!important;height:42px!important;line-height:42px!important;background:rgba(255,255,255,.94)!important;color:#344054!important;font-weight:800}.main-leaflet .leaflet-control-attribution{font-size:8px}.map-syria-label{position:absolute;right:18px;bottom:calc(35dvh + 22px);z-index:500;padding:7px 11px;border-radius:999px;background:rgba(255,255,255,.88);color:#344054;font:800 10px Cairo,Arial,sans-serif;box-shadow:0 6px 18px rgba(16,24,40,.1);pointer-events:none}.price-marker{min-width:70px;padding:6px 9px;border:2px solid #fff;border-radius:14px;background:#0b7a68;color:#fff;font:800 10px/1.2 Cairo,Arial,sans-serif;text-align:center;box-shadow:0 8px 18px rgba(16,24,40,.22);white-space:nowrap}.price-marker.rent{background:#1677a8}.price-marker.sale{background:#b86b08}.main-popup{direction:rtl;text-align:right;font:600 12px/1.6 Cairo,Arial,sans-serif;min-width:145px}.main-popup b{font-size:13px;color:#16201f}.main-popup div{color:#0b7a68;font-weight:900}`;document.head.appendChild(s)}
  function create(){if(!window.L||!document.getElementById(MAP_ID))return false;if(map)return true;inject();const host=document.getElementById(MAP_ID);host.querySelectorAll('.main-leaflet').forEach(x=>x.remove());const shell=document.createElement('div');shell.className='main-leaflet';host.appendChild(shell);map=L.map(shell,{zoomControl:true,minZoom:5,maxZoom:18,maxBounds:BOUNDS,maxBoundsViscosity:1,zoomSnap:.25,zoomDelta:.5}).setView(CENTER,7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);markers=L.layerGroup().addTo(map);const tag=document.createElement('div');tag.className='map-syria-label';tag.textContent='سورية';shell.appendChild(tag);map.fitBounds(BOUNDS,{padding:[24,24]});setTimeout(()=>map.invalidateSize(),150);loadPins();return true}
  async function loadPins(){if(!map||!window.db||!markers)return;markers.clearLayers();const {data,error}=await db.from('properties').select('id,title,price,address,latitude,longitude,status,deal_type').in('status',['published','sold','rented']).not('latitude','is',null).not('longitude','is',null);if(error)return;(data||[]).forEach(x=>{const el=L.divIcon({className:'',html:`<div class="price-marker ${x.deal_type==='rent'?'rent':'sale'}">${esc(money(x.price))}</div>`,iconSize:[100,38],iconAnchor:[50,38]});L.marker([Number(x.latitude),Number(x.longitude)],{icon:el}).addTo(markers).bindPopup(`<div class="main-popup"><b>${esc(x.title)}</b><div>${esc(money(x.price))}</div><small>${esc(x.address||'الموقع عند التواصل')}</small></div>`)});const pts=(data||[]).map(x=>[Number(x.latitude),Number(x.longitude)]).filter(x=>Number.isFinite(x[0])&&Number.isFinite(x[1]));if(pts.length)map.fitBounds(pts,{padding:[40,40],maxZoom:14})}
  function locate(){if(!map)return;map.locate({setView:true,maxZoom:14,enableHighAccuracy:true})}
  function wire(){document.getElementById('zoomIn')?.addEventListener('click',()=>map?.zoomIn());document.getElementById('zoomOut')?.addEventListener('click',()=>map?.zoomOut());document.getElementById('resetMap')?.addEventListener('click',()=>map?.fitBounds(BOUNDS,{padding:[24,24],duration:600}));document.getElementById('locateBtn')?.addEventListener('click',locate)}
  function boot(){if(!create()){setTimeout(boot,300);return}wire()}
  setTimeout(boot,250);window.MainGlobe={reload:loadPins,focus:(lng,lat,z=13)=>map?.setView([lat,lng],z,{animate:true}),getMap:()=>map};
})();