(()=>{
  const MAP_ID='publicMap';
  const CENTER=[36.0,35.6];
  const style={version:8,sources:{satellite:{type:'raster',tiles:['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:19,attribution:'Tiles © Esri'},osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,maxzoom:19,attribution:'© OpenStreetMap contributors'}},layers:[{id:'base',type:'raster',source:'satellite'}]};
  let map=null;
  let markerLayer=[];
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const money=v=>v==null||v===''?'السعر عند التواصل':`${Number(v).toLocaleString('ar-SY')} ل.س`;
  function inject(){if(document.getElementById('mainGlobeCss'))return;const s=document.createElement('style');s.id='mainGlobeCss';s.textContent=`#publicMap{background:#08111d;overflow:hidden}.leaflet-container{display:none!important}.main-globe-shell{position:absolute;inset:0;z-index:2}.main-globe-shell .maplibregl-canvas{outline:none}.main-globe-shell .maplibregl-ctrl-group{background:rgba(15,23,42,.72);backdrop-filter:blur(14px);border:1px solid rgba(255,255,255,.14);border-radius:16px;overflow:hidden;box-shadow:0 10px 30px rgba(0,0,0,.2)}.main-globe-shell .maplibregl-ctrl button{width:42px;height:42px}.globe-pin{width:34px;height:34px;border-radius:50% 50% 50% 0;transform:rotate(-45deg);display:grid;place-items:center;background:linear-gradient(145deg,#16a085,#075e4f);border:3px solid rgba(255,255,255,.95);box-shadow:0 8px 22px rgba(0,0,0,.32)}.globe-pin span{transform:rotate(45deg);font-size:15px}.globe-popup{font-family:Cairo,Arial,sans-serif;direction:rtl;min-width:170px}.globe-popup b{display:block;margin-bottom:5px}.globe-popup small{opacity:.72}.globe-hint{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);z-index:5;pointer-events:none;padding:8px 13px;border-radius:999px;background:rgba(15,23,42,.42);color:#fff;font:600 12px Cairo,Arial,sans-serif;backdrop-filter:blur(8px);opacity:0;transition:opacity .35s}.globe-hint.show{opacity:1}`;document.head.appendChild(s)}
  function create(){if(!window.maplibregl||!document.getElementById(MAP_ID))return false;if(map)return true;inject();const host=document.getElementById(MAP_ID);host.querySelectorAll('.leaflet-pane,.leaflet-control-container,.leaflet-marker-icon,.leaflet-marker-shadow').forEach(x=>x.remove());const shell=document.createElement('div');shell.className='main-globe-shell';host.appendChild(shell);map=new maplibregl.Map({container:shell,style,center:CENTER,zoom:1.55,projection:{type:'globe'},pitch:0,attributionControl:false,dragRotate:true,renderWorldCopies:false});map.addControl(new maplibregl.NavigationControl({showCompass:true}), 'bottom-left');map.addControl(new maplibregl.AttributionControl({compact:true}));map.on('load',()=>{setTimeout(()=>map.resize(),80);loadPins();});return true}
  async function loadPins(){if(!map||!window.db)return;markerLayer.forEach(m=>m.remove());markerLayer=[];const {data,error}=await db.from('properties').select('id,title,price,address,latitude,longitude,status').in('status',['published','sold','rented']).not('latitude','is',null).not('longitude','is',null);if(error)return;(data||[]).forEach(x=>{const el=document.createElement('div');el.className='globe-pin';el.innerHTML='<span>⌂</span>';const popup=new maplibregl.Popup({offset:20,closeButton:true}).setHTML(`<div class="globe-popup"><b>${esc(x.title)}</b><div>${esc(money(x.price))}</div><small>${esc(x.address||'الموقع عند التواصل')}</small></div>`);const m=new maplibregl.Marker({element:el,anchor:'bottom'}).setLngLat([Number(x.longitude),Number(x.latitude)]).setPopup(popup).addTo(map);markerLayer.push(m)});}
  function wire(){document.getElementById('zoomIn')?.addEventListener('click',()=>map?.zoomIn());document.getElementById('zoomOut')?.addEventListener('click',()=>map?.zoomOut());document.getElementById('resetMap')?.addEventListener('click',()=>map?.flyTo({center:CENTER,zoom:1.55,duration:900}));document.getElementById('locateBtn')?.addEventListener('click',()=>{if(!map)return;if(!navigator.geolocation)return;map.once('movestart',()=>{});navigator.geolocation.getCurrentPosition(p=>map.flyTo({center:[p.coords.longitude,p.coords.latitude],zoom:11,duration:1200}),()=>{});});}
  function boot(){if(!create()){setTimeout(boot,300);return}wire();}
  new MutationObserver(()=>{if(!map)boot()}).observe(document.body,{childList:true,subtree:true});
  setTimeout(boot,250);
  window.MainGlobe={reload:loadPins,focus:(lng,lat,z=11)=>map?.flyTo({center:[lng,lat],zoom:z,duration:1000})};
})();